upload_image:
  name: "Belegbild hochladen"
  description: "Speichert ein vom Frontend 체bergebenes Base64-Bild im Upload-Ordner und startet OCR."
  fields:
    filename:
      name: Datei
      description: "Dateiname, z. B. kassenzettel.jpg"
      example: "receipt.jpg"
      required: true
      selector:
        text:
    image_data:
      name: Base64-Daten
      description: "data:image/jpeg;base64,..."
      example: "data:image/jpeg;base64,/9j/4AAQ..."
      required: true
      selector:
        text:

scan_receipts:
  name: "OCR-Scan durchf체hren"
  description: "Scant den Upload-Ordner erneut und aktualisiert receipts.json."
  fields:
    folder_path:
      name: Ordnerpfad
      description: "Standard: /config/www/receipts_uploads"
      required: false
      selector:
        text:

get_receipt_details:
  name: "Belegdetails finden"
  description: "Findet passende Receipt-Daten anhand Gesamtbetrag, H채ndler und optional Datum."
  fields:
    store:
      name: H채ndler
      description: "z. B. REWE, Lidl, Aldi"
      example: "REWE"
      required: false
      selector:
        text:
    total:
      name: Gesamtbetrag
      description: "Betrag der Buchung"
      example: "20.47"
      required: true
      selector:
        text:
    date:
      name: Datum
      description: "Optionales Datum, z. B. 2025-10-21"
      example: "2025-10-21"
      required: false
      selector:
        text:
